#!/bin/sh

# Using senka.me

dir=`dirname $0`

mkdir -p $dir/Output

echo "fetching data from senka.me..."

for i in `seq ${1-1} ${2-20}` ; do
  if [ ! -s $dir/Output/$i ]; then
    echo "  server #$i"
    curl -s https://www.senka.me/server/$i/ > $dir/Output/$i
    if grep --quiet cloudflare $dir/Output/$i ; then
      echo "    cloudflared"
      rm $dir/Output/$i
      echo "  waiting..."
      sleep 5
    elif [ ! -s $dir/Output/$i ]; then
      echo "    dropped"
      rm $dir/Output/$i
    else
      echo "    done"
      echo "  waiting..."
      sleep ${1:-5}
    fi
  fi
done

echo > $dir/Output/ranks.js

for i in `seq 1 20` ; do
  if [ -s $dir/Output/$i ]; then
    cat $dir/Output/$i \
    | grep SenkaChart \
    | sed "s/SenkaChart/rankPointData$i/" \
    | sed "s/<script>//" \
    | sed "s/<\/script>//" \
    | sed 's/^[ \t]*//' \
    | sed 's/位//g' \
    >> $dir/Output/ranks.js
  else
    rm $dir/Output/ranks.js
    echo "rerun required"
    exit
  fi
done

cat >> $dir/Output/ranks.js << GenJS

var servers = [
    rankPointData1, rankPointData2, rankPointData3, rankPointData4, rankPointData5,
    rankPointData6, rankPointData7, rankPointData8, rankPointData9, rankPointData10,
    rankPointData11, rankPointData12, rankPointData13, rankPointData14, rankPointData15,
    rankPointData16, rankPointData17, rankPointData18, rankPointData19, rankPointData20
];

var serverNames = [
    "Yokosuka", "Kure", "Sasebo", "Maizuru", "Ominato", "Truk", "Lingga", "Rabaul", "Shortland", "Buin",
    "Tawi-Tawi", "Palau", "Brunei", "Hitokappu", "Paramushir", "Sukumo", "Kanoya", "Iwagawa", "Saiki", "Hashirajima",
];

var s = "";
for (var i = 0; i < servers.length; ++i) {
    s += "|-\n|" + serverNames[i] + "\n";
    for (var ranking of servers[i].RankPoint) {
        s += "|" + ranking.Value[ranking.Value.length - 1] + "\n";
    }
}
console.log(s);

GenJS

node $dir/Output/ranks.js > $dir/Output/ranks

echo "done"
