#!/bin/sh

mkdir -p Output/CG

while read line
do
    arr=($line)
    url=${arr[0]}
    file=${arr[1]}
    echo $file
    curl -v "$url" 2>&1 > "Output/CG/$file.swf" | grep Last-Modified
    java -jar "/c/Program Files (x86)/FFDec/ffdec.jar" -format image:png -export image Output/CG/$file Output/CG/$file.swf | grep finished
done < Data/CG/Updated
